name: troupe-multi-isolated

services:
  init:
    image: troupe-key-make
    pull_policy: never # Image does not exist on dockerhub.
    build:
      context: ../key-maker
      dockerfile: key-maker.Dockerfile
    command: > # Create indentities and distribute to the respective services.
      /bin/sh -c 'mkdir -p echo-server
                  mkdir -p echo-client
                  node /key-maker/mkid.mjs --privkeyfile=keys/relay.priv --idfile=keys/relay.id
                  node /key-maker/mkid.mjs --outfile=keys/echo-server.json
                  node /key-maker/mkid.mjs --outfile=keys/echo-client.json
                  node /key-maker/mkaliases.js --include=keys/echo-server.json --include=keys/echo-client.json --outfile=keys/aliases.json
                  cp keys/relay.priv /key-maker/relay/
                  cp keys/relay.id /key-maker/relay/
                  cp keys/relay.id /key-maker/echo-server/
                  cp keys/echo-server.json /key-maker/echo-server/
                  cp keys/relay.id /key-maker/echo-client/
                  cp keys/echo-client.json /key-maker/echo-client/
                  cp keys/aliases.json /key-maker/echo-client/'
    volumes:
      - relay-key:/key-maker/relay
      - server-key:/key-maker/echo-server
      - client-key:/key-maker/echo-client
    restart: no

  echo-server:
    container_name: server
    image: troupe-integrity
    networks:
      - internal_only
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - server-key:/Troupe/ids
    command: /bin/sh -c "/Troupe/network.sh /Troupe/examples/network/echo/echo-server.trp --id=ids/echo-server.json"
    
  echo-client:
    container_name: client
    image: troupe-integrity
    networks:
      - internal_only
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - client-key:/Troupe/ids
    command: /bin/sh -c "/Troupe/network.sh /Troupe/examples/network/echo/echo-client.trp --id=ids/echo-client.json --aliases=ids/aliases.json"
    
networks:
  internal_only:
    driver: bridge # Use the standard container network driver.
    internal: true # Make the compose network completely isolated.

volumes:
  relay-key:
  server-key:
  client-key:
    
