start:
	docker compose -f docker-compose.yaml up

stop:
	docker compose -f docker-compose.yaml down --volumes

start-no-relay:
	docker compose -f docker-compose-isolated.yaml up

stop-no-relay:
	docker compose -f docker-compose-isolated.yaml down --volumes
