name: troupe-parallel-multi

services:
  # The init service generates keys and ids for the services.
  init:
    image: troupe-key-make
    pull_policy: never # Image does not exist on dockerhub.
    build:
      context: ../key-maker
      dockerfile: key-maker.Dockerfile
    command: >- # Create indentities and distribute to the respective services.
      /bin/sh -c 'mkdir -p one
                  mkdir -p two
                  mkdir -p three
                  node /key-maker/mkid.mjs --privkeyfile=keys/relay.priv --idfile=keys/relay.id
                  node /key-maker/mkid.mjs --outfile=keys/one.json
                  node /key-maker/mkid.mjs --outfile=keys/two.json
                  node /key-maker/mkid.mjs --outfile=keys/three.json
                  node /key-maker/mkaliases.js --include=keys/one.json\
                                               --include=keys/two.json\
                                               --include=keys/three.json\
                                               --outfile=keys/aliases.json
                  cp keys/relay.priv /key-maker/relay/
                  cp keys/relay.id /key-maker/relay/
                  cp keys/relay.id /key-maker/three/
                  cp keys/three.json /key-maker/three/
                  cp keys/aliases.json /key-maker/three/
                  cp keys/relay.id /key-maker/two/
                  cp keys/two.json /key-maker/two/
                  cp keys/aliases.json /key-maker/two/
                  cp keys/relay.id /key-maker/one/
                  cp keys/one.json /key-maker/one/
                  cp keys/aliases.json /key-maker/one/'
    volumes:
      - relay-key:/key-maker/relay
      - one-key:/key-maker/one
      - two-key:/key-maker/two
      - three-key:/key-maker/three
    restart: no
    
  relay: # Troupe relay service in the compose network.
    container_name: relay
    image: troupe-relay
    pull_policy: never # Image does not exist on dockerhub.
    build: # Build the image if it does not exist.
      context: ../../relay
      dockerfile: relay.Dockerfile
    networks: # Restrict to the isolated network.
      - internal_only
    ports:
      - 5555:5555
    depends_on:
      init: # Only start after keys and ids are created.
        condition: service_completed_successfully
    volumes:
      - relay-key:/relay/keys
    command: node relay.mjs

  three:
    container_name: three
    image: troupe-integrity
    pull_policy: never # Image does not exist on dockerhub.
    build: # Build the image if it does not exist.
      dockerfile: ../../dev-integrity.Dockerfile
    networks: # Restrict to the isolated network.
      - internal_only
    depends_on:
      init: # Only start after keys and ids are created.
        condition: service_completed_successfully
    volumes:
      - three-key:/Troupe/ids
    command: >-
      /bin/sh -c '/Troupe/network.sh\
                  /Troupe/examples/network/parallel/zero.trp\
                  --id=/Troupe/ids/three.json\
                  --rspawn=true\
                  --aliases=/Troupe/ids/aliases.json\
                  --stdiolev={}\
                  --relay=/dns4/relay/tcp/5555/ws/p2p/$(cat ids/relay.id)'

  two:
    container_name: two
    image: troupe-integrity
    pull_policy: never
    networks:
      - internal_only
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - two-key:/Troupe/ids
    command: >-
      /bin/sh -c '/Troupe/network.sh\
                  /Troupe/examples/network/parallel/two.trp\
                  --id=/Troupe/ids/two.json\
                  --aliases=/Troupe/ids/aliases.json\
                  --relay=/dns4/relay/tcp/5555/ws/p2p/$(cat ids/relay.id)' 
                  
  one:
    container_name: one
    image: troupe-integrity
    pull_policy: never # Image does not exist on dockerhub.
    build: # Build the image if it does not exist.
      dockerfile: ../../dev-integrity.Dockerfile
    networks: # Restrict to the isolated network.
      - internal_only
    depends_on:
      init: # Only start after keys and ids are created.
        condition: service_completed_successfully
    volumes:
      - one-key:/Troupe/ids
    command: >-
      /bin/sh -c '/Troupe/network.sh\
                  /Troupe/examples/network/parallel/zero.trp\
                  --id=ids/one.json\
                  --rspawn=true\
                  --aliases=ids/aliases.json\
                  --stdiolev={}\
                  --relay=/dns4/relay/tcp/5555/ws/p2p/$(cat ids/relay.id)'
    
networks:
  internal_only: # Network for isolating the composed containers.
    driver: bridge # Use the standard container network driver.
    internal: true # Make the compose network completely isolated.

volumes:
  relay-key:  # Volume for relay resources.
  one-key:
  two-key:
  three-key: 
    
