name: troupe-pingpong-multi

services:
  # The init service generates keys and ids for the services.
  init:
    image: troupe-key-make
    pull_policy: never # Image does not exist on dockerhub.
    build:
      context: ../key-maker
      dockerfile: key-maker.Dockerfile
    command: > # Create indentities and distribute to the respective services.
      /bin/sh -c 'mkdir -p pingpong-dialer
                  mkdir -p pingpong-listener
                  node /key-maker/mkid.mjs --privkeyfile=keys/relay.priv --idfile=keys/relay.id
                  node /key-maker/mkid.mjs --outfile=keys/pingpong-listener.json
                  node /key-maker/mkid.mjs --outfile=keys/pingpong-dialer.json
                  node /key-maker/mkaliases.js --include=keys/pingpong-listener.json\
                                               --include=keys/pingpong-dialer.json\
                                               --outfile=keys/aliases.json
                  cp keys/relay.priv /key-maker/relay/
                  cp keys/relay.id /key-maker/relay/
                  cp keys/relay.id /key-maker/pingpong-listener/
                  cp keys/pingpong-listener.json /key-maker/pingpong-listener/
                  cp keys/aliases.json /key-maker/pingpong-listener/
                  cp keys/relay.id /key-maker/pingpong-dialer/
                  cp keys/pingpong-dialer.json /key-maker/pingpong-dialer/
                  cp keys/aliases.json /key-maker/pingpong-dialer/'
    volumes:
      - relay-key:/key-maker/relay
      - listener-key:/key-maker/pingpong-listener
      - dialer-key:/key-maker/pingpong-dialer
    restart: no
    
  relay: # Troupe relay service in the compose network.
    image: troupe-relay
    pull_policy: never # Image does not exist on dockerhub.
    build: # Build the image if it does not exist.
      context: ../../relay
      dockerfile: relay.Dockerfile
    networks: # Restrict to the isolated network.
      - internal_only
    depends_on:
      init: # Only start after keys and ids are created.
        condition: service_completed_successfully
    volumes:
      - relay-key:/relay/keys
    command: node relay.mjs

  pingpong-listener:
    image: troupe-integrity
    pull_policy: never # Image does not exist on dockerhub.
    build: # Build the image if it does not exist.
      dockerfile: ../../dev-integrity.Dockerfile
    networks: # Restrict to the isolated network.
      - internal_only
    depends_on:
      init: # Only start after keys and ids are created.
        condition: service_completed_successfully
    volumes:
      - listener-key:/Troupe/ids
    command: > # Run the echo server. Note the relay has the dns "relay".
      /bin/sh -c '/Troupe/network.sh\
                  /Troupe/examples/network/pingpong/zero.trp\
                  --id=/Troupe/ids/pingpong-listener.json\
                  --rspawn=true\
                  --aliases=/Troupe/ids/aliases.json\
                  --stdiolev={}\
                  --relay=/dns4/relay/tcp/5555/ws/p2p/$(cat ids/relay.id)'

  pingpong-dialer:
    image: troupe-integrity
    pull_policy: never # Image does not exist on dockerhub.
    build: # Build the image if it does not exist.
      dockerfile: ../../dev-integrity.Dockerfile
    networks: # Restrict to the isolated network.
      - internal_only
    depends_on:
      init: # Only start after keys and ids are created.
        condition: service_completed_successfully
    volumes:
      - dialer-key:/Troupe/ids
    command: > # Run the echo client.
      /bin/sh -c '/Troupe/network.sh\
                  /Troupe/examples/network/pingpong/p2ppingpong.trp\
                  --id=ids/pingpong-dialer.json --aliases=ids/aliases.json\
                  --relay=/dns4/relay/tcp/5555/ws/p2p/$(cat ids/relay.id)'
    
networks:
  internal_only: # Network for isolating the composed containers.
    driver: bridge # Use the standard container network driver.
    internal: true # Make the compose network completely isolated.

volumes:
  relay-key:  # Volume for relay resources.
  dialer-key: # Volume for dialer resources.
  listener-key: # Volume for listener resources.
    
